baseURL = 'https://corvallisfoodblogger.github.io/corvallis_food_blog/'
languageCode = 'en-us'
title = 'Corvallis Food Blog'
theme = "ananke"
enableRobotsTXT = true

[params]
  subtitle = 'Reviews of Corvallis Restaurants'
  [params.contact]
    email = 'corvallisfoodblog@gmail.com'
    
[services.disqus]
  shortname = 'corvallis-food-blog'
